version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: docker/dockerfile
    depends_on:
      - db
    volumes:
      - ./:/go/src/app
    tty: true

  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/0-schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


volumes:
  mysql_volume: